### ISSUE TITLE
Error: EACCES: permission denied, open '/deez/.config/Deezloader Remix/logs/2019-09-21-22.22.33.txt',

### ISSUE THREAD

**Issue by Gilinho** [Bockiii/deezloadermx-docker#6]
After today updates the container fails to work. In the logs I have the following.

```
fs.js:114,
    throw err;,
    ^,
,
Error: EACCES: permission denied, open '/deez/.config/Deezloader Remix/logs/2019-09-21-22.22.33.txt',
    at Object.openSync (fs.js:443:3),
    at Object.writeFileSync (fs.js:1194:35),
    at Object.appendFileSync (fs.js:1240:6),
    at Object.<anonymous> (/deezloaderremix/app/utils/logger.js:9:4),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Module.require (internal/modules/cjs/loader.js:692:17),
    at require (internal/modules/cjs/helpers.js:25:18),
    at Object.<anonymous> (/deezloaderremix/app/app.js:28:16),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12),
    at startup (internal/bootstrap/node.js:283:19),
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),,
4,
    throw err;,
    ^,
,
Error: EACCES: permission denied, open '/deez/.config/Deezloader Remix/logs/2019-09-21-22.22.34.txt',
    at Object.openSync (fs.js:443:3),
    at Object.writeFileSync (fs.js:1194:35),
    at Object.appendFileSync (fs.js:1240:6),
    at Object.<anonymous> (/deezloaderremix/app/utils/logger.js:9:4),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Module.require (internal/modules/cjs/loader.js:692:17),
    at require (internal/modules/cjs/helpers.js:25:18),
    at Object.<anonymous> (/deezloaderremix/app/app.js:28:16),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12),
    at startup (internal/bootstrap/node.js:283:19),
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),,
4,
    throw err;,
    ^,
,
Error: EACCES: permission denied, open '/deez/.config/Deezloader Remix/logs/2019-09-21-22.22.35.txt',
    at Object.openSync (fs.js:443:3),
    at Object.writeFileSync (fs.js:1194:35),
    at Object.appendFileSync (fs.js:1240:6),
    at Object.<anonymous> (/deezloaderremix/app/utils/logger.js:9:4),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Module.require (internal/modules/cjs/loader.js:692:17),
    at require (internal/modules/cjs/helpers.js:25:18),
    at Object.<anonymous> (/deezloaderremix/app/app.js:28:16),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12),
    at startup (internal/bootstrap/node.js:283:19),
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),,
4,
    throw err;,
    ^,
,
Error: EACCES: permission denied, open '/deez/.config/Deezloader Remix/logs/2019-09-21-22.22.36.txt',
    at Object.openSync (fs.js:443:3),
    at Object.writeFileSync (fs.js:1194:35),
    at Object.appendFileSync (fs.js:1240:6),
    at Object.<anonymous> (/deezloaderremix/app/utils/logger.js:9:4),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Module.require (internal/modules/cjs/loader.js:692:17),
    at require (internal/modules/cjs/helpers.js:25:18),
    at Object.<anonymous> (/deezloaderremix/app/app.js:28:16),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12),
    at startup (internal/bootstrap/node.js:283:19),
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),
```

**Comment by Gilinho** [comment]
Had  to use  the bellow to make it work again
PUID	0
PGID	0

**Comment by Bockiii** [comment]
Hi, thanks for the bug report, I will see what I can do. 

Explanation:  Everything until now was run as root (0:0) which led to a bunch of issues with folders, that's why I completely changed the way the user management works. Luckily, that also has a way of fixing this (I think ;D ). Will test and let you know. Then you can run it as a different user again.

**Comment by Bockiii** [comment]
Fixed already. Only had to add a chown to the config folder for the executing user.

You can now go back to the standard.
